# Generated by Django 5.2.12 on 2026-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус доступности')),
            ],
            options={
                'verbose_name': 'Доступность объекта',
                'verbose_name_plural': '4. Доступность объектов',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': '3. Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '2. Категории',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': '1. Районы',
            },
        ),
        migrations.CreateModel(
            name='OwnershipEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Субъект собственности')),
            ],
            options={
                'verbose_name': 'Субъект собственности',
                'verbose_name_plural': '5. Субъекты собственности',
            },
        ),
        migrations.CreateModel(
            name='PassportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус паспорта')),
            ],
            options={
                'verbose_name': 'Статус паспорта',
                'verbose_name_plural': '8. Статусы паспортов',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ответственный орган')),
            ],
            options={
                'verbose_name': 'Ответственный орган',
                'verbose_name_plural': '6. Ответственные органы',
            },
        ),
        migrations.CreateModel(
            name='StreetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория улицы')),
            ],
            options={
                'verbose_name': 'Категория улицы',
                'verbose_name_plural': '7. Категории улицы',
            },
        ),
    ]
