# Generated by Django 5.2.13 on 2026-04-17 20:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_coveragecategory_street_alter_passportstatus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id'], 'verbose_name': 'Район города', 'verbose_name_plural': '1. Районы городов'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.AddField(
            model_name='district',
            name='akim_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Акима'),
        ),
        migrations.AddField(
            model_name='district',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Границы района (полигон)'),
        ),
        migrations.AddField(
            model_name='district',
            name='gerb',
            field=models.ImageField(blank=True, null=True, upload_to='districts/logos/', verbose_name='Герб района'),
        ),
        migrations.AddField(
            model_name='district',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на казахском'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском'),
        ),
        migrations.AddField(
            model_name='district',
            name='pronunciation_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Произношение на казахском'),
        ),
        migrations.AddField(
            model_name='district',
            name='pronunciation_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Произношение на русском'),
        ),
    ]
