# Generated by Django 5.2.13 on 2026-04-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_alter_district_options_remove_district_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='pronunciation_kz',
        ),
        migrations.RemoveField(
            model_name='district',
            name='pronunciation_ru',
        ),
    ]
