# Generated by Django 5.2.13 on 2026-04-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_remove_district_pronunciation_kz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id'], 'verbose_name': 'Район города', 'verbose_name_plural': 'Районы городов'},
        ),
    ]
