# Generated by Django 5.2.13 on 2026-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_alter_district_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name_ru'], 'verbose_name': 'Категория объекта', 'verbose_name_plural': 'Категории объектов'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2196F3', help_text='Пример: #FF5722', max_length=7, verbose_name='Цвет маркера (HEX)'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
