# Generated by Django 5.2.13 on 2026-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_alter_category_color_alter_category_name_kz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['-id'], 'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='name',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование вида деятельности на казахском'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование вида деятельности на русском'),
            preserve_default=False,
        ),
    ]
