# Generated by Django 5.2.12 on 2026-04-01 22:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('objects', '0003_entrancegroup_has_audio_guide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccessibilityObject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование организации')),
                ('full_name_kz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование на каз. языке')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('floors_count', models.PositiveIntegerField(default=1, verbose_name='Количество этажей')),
                ('build_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Точка на карте')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.activitytype', verbose_name='Вид деятельности')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.category', verbose_name='Категория объекта')),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.district', verbose_name='Район')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ownership_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.ownershipentity', verbose_name='Субъект собственности')),
                ('responsible_body', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.responsiblebody', verbose_name='Ответственный орган')),
            ],
            options={
                'verbose_name': 'historical Паспорт объекта',
                'verbose_name_plural': 'historical 1. Паспорта объектов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
