# Generated by Django 5.2.12 on 2026-04-01 22:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('objects', '0004_historicalaccessibilityobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название остановки')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Точка на карте')),
                ('has_pavilion', models.BooleanField(default=False, verbose_name='Наличие павильона')),
                ('has_electronic_board', models.BooleanField(default=False, verbose_name='Электронное табло')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='Доступна для МГН')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.district')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': '4. Остановки транспорта',
            },
        ),
        migrations.CreateModel(
            name='SubObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип здания/название')),
                ('floors', models.PositiveIntegerField(verbose_name='Этажность')),
                ('build_year', models.PositiveIntegerField(verbose_name='Год постройки')),
                ('parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_objects', to='objects.accessibilityobject')),
            ],
            options={
                'verbose_name': 'Дополнительный объект',
                'verbose_name_plural': 'Доп. объекты на территории',
            },
        ),
    ]
