# Generated by Django 5.2.13 on 2026-04-19 21:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_alter_busstop_options_busstop_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityobject',
            options={'verbose_name': 'Паспорт объекта', 'verbose_name_plural': '1. Паспорта объектов'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccessibilityobject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Паспорт объекта', 'verbose_name_plural': 'historical 1. Паспорта объектов'},
        ),
        migrations.AlterModelOptions(
            name='objectaccessibilityresult',
            options={'verbose_name': 'Заключение по разделу', 'verbose_name_plural': '3. Заключения о доступности'},
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка (Point)'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Контур (Polygon)'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='not_in_tx',
            field=models.BooleanField(default=False, verbose_name='Нет в ТХ'),
        ),
        migrations.AlterField(
            model_name='entrancegroup',
            name='has_braille',
            field=models.BooleanField(default=False, verbose_name='Наличие Брайля'),
        ),
        migrations.AlterField(
            model_name='entrancegroup',
            name='has_call_button',
            field=models.BooleanField(default=False, verbose_name='Кнопка вызова'),
        ),
        migrations.AlterField(
            model_name='entrancegroup',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='Наличие пандуса'),
        ),
        migrations.AlterField(
            model_name='entrancegroup',
            name='has_visual_info',
            field=models.BooleanField(default=False, verbose_name='Визуальная информация'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка (Point)'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Контур (Polygon)'),
        ),
        migrations.AlterField(
            model_name='infotelecom',
            name='has_audio_guide',
            field=models.BooleanField(default=False, verbose_name='Аудиогид'),
        ),
        migrations.AlterField(
            model_name='infotelecom',
            name='has_visual_info',
            field=models.BooleanField(default=False, verbose_name='Электронное табло'),
        ),
        migrations.AlterField(
            model_name='infotelecom',
            name='induction_loop',
            field=models.BooleanField(default=False, verbose_name='Индукционная петля'),
        ),
        migrations.AlterField(
            model_name='movementways',
            name='has_handrails',
            field=models.BooleanField(default=False, verbose_name='Наличие поручней'),
        ),
        migrations.AlterField(
            model_name='movementways',
            name='tactile_indicators',
            field=models.BooleanField(default=False, verbose_name='Тактильные указатели'),
        ),
        migrations.AlterField(
            model_name='movementways',
            name='width_ok',
            field=models.BooleanField(default=False, verbose_name='Ширина путей в норме'),
        ),
        migrations.AlterField(
            model_name='objectaccessibilityresult',
            name='k_status',
            field=models.CharField(default='not_accessible', max_length=20, verbose_name='К'),
        ),
        migrations.AlterField(
            model_name='objectaccessibilityresult',
            name='o_status',
            field=models.CharField(default='not_accessible', max_length=20, verbose_name='О'),
        ),
        migrations.AlterField(
            model_name='objectaccessibilityresult',
            name='s_status',
            field=models.CharField(default='not_accessible', max_length=20, verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='objectaccessibilityresult',
            name='section',
            field=models.CharField(max_length=50, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='objectaccessibilityresult',
            name='z_status',
            field=models.CharField(default='not_accessible', max_length=20, verbose_name='З'),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='image',
            field=models.ImageField(upload_to='objects/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='objectterritory',
            name='entrance_width_ok',
            field=models.BooleanField(default=False, verbose_name='Ширина прохода > 90см'),
        ),
        migrations.AlterField(
            model_name='objectterritory',
            name='parking_has_disabled_spots',
            field=models.BooleanField(default=False, verbose_name='Парковка для МГН'),
        ),
        migrations.AlterField(
            model_name='sanitaryrooms',
            name='toilet_accessible',
            field=models.BooleanField(default=False, verbose_name='Спец. туалет доступен'),
        ),
        migrations.AlterField(
            model_name='servicezones',
            name='counter_height_ok',
            field=models.BooleanField(default=False, verbose_name='Высота стоек в норме'),
        ),
        migrations.AlterField(
            model_name='stopaccessibility',
            name='has_dedicated_lane',
            field=models.BooleanField(default=False, verbose_name='Выделенная полоса'),
        ),
        migrations.AlterField(
            model_name='stoppavilion',
            name='has_benches',
            field=models.BooleanField(default=False, verbose_name='Скамейки'),
        ),
        migrations.AlterField(
            model_name='stoppavilion',
            name='has_lighting',
            field=models.BooleanField(default=False, verbose_name='Освещение'),
        ),
        migrations.AlterField(
            model_name='stopplatform',
            name='has_tactile_tile',
            field=models.BooleanField(default=False, verbose_name='Тактильная плитка'),
        ),
        migrations.AlterField(
            model_name='stopplatform',
            name='is_level_with_bus',
            field=models.BooleanField(default=False, verbose_name='В один уровень с краем дороги'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
