# Generated by Django 5.2.12 on 2026-04-01 20:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование организации')),
                ('full_name_kz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование на каз. языке')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('floors_count', models.PositiveIntegerField(default=1, verbose_name='Количество этажей')),
                ('build_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Точка на карте')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.activitytype', verbose_name='Вид деятельности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.category', verbose_name='Категория объекта')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.district', verbose_name='Район')),
                ('ownership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.ownershipentity', verbose_name='Субъект собственности')),
                ('responsible_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.responsiblebody', verbose_name='Ответственный орган')),
            ],
            options={
                'verbose_name': 'Паспорт объекта',
                'verbose_name_plural': 'Паспорта объектов',
            },
        ),
    ]
