# Generated by Django 5.2.12 on 2026-04-01 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityobject',
            options={'verbose_name': 'Паспорт объекта', 'verbose_name_plural': '1. Паспорта объектов'},
        ),
        migrations.CreateModel(
            name='EntranceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ramp', models.BooleanField(default=False, verbose_name='Наличие пандуса')),
                ('ramp_slope_ok', models.BooleanField(default=False, verbose_name='Уклон пандуса соответствует норме')),
                ('has_call_button', models.BooleanField(default=False, verbose_name='Наличие кнопки вызова')),
                ('door_width_ok', models.BooleanField(default=False, verbose_name='Ширина дверного проема (не менее 90см)')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_group', to='objects.accessibilityobject')),
            ],
            options={
                'verbose_name': 'Входная группа',
                'verbose_name_plural': '3. Входные группы',
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='objects/%Y/%m/%d/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='objects.accessibilityobject')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
        migrations.CreateModel(
            name='ObjectTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_not_required', models.BooleanField(default=False, verbose_name='Не требуется')),
                ('entrance_width_ok', models.BooleanField(default=False, verbose_name='Ширина прохода (не менее 90см)')),
                ('entrance_actual_value', models.CharField(blank=True, max_length=255, verbose_name='Фактическое значение')),
                ('parking_not_required', models.BooleanField(default=False, verbose_name='Автостоянка: не требуется')),
                ('parking_has_disabled_spots', models.BooleanField(default=False, verbose_name='Наличие мест для инвалидов')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='territory', to='objects.accessibilityobject')),
            ],
            options={
                'verbose_name': 'Территория объекта',
                'verbose_name_plural': '2. Территории объектов',
            },
        ),
    ]
