# Generated by Django 5.2.12 on 2026-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_accessibilityobject_options_entrancegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancegroup',
            name='has_audio_guide',
            field=models.BooleanField(default=False, verbose_name='Звуковой маяк/гид'),
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_braille',
            field=models.BooleanField(default=False, verbose_name='Наличие шрифта Брайля'),
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_tactile_path',
            field=models.BooleanField(default=False, verbose_name='Тактильные полосы'),
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_visual_info',
            field=models.BooleanField(default=False, verbose_name='Визуальное табло/инфо'),
        ),
    ]
