# Generated by Django 5.2.12 on 2026-04-02 09:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_coveragecategory_street_alter_passportstatus_name'),
        ('objects', '0005_busstop_subobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'verbose_name': 'Паспорт остановки', 'verbose_name_plural': '2. Паспорта остановок'},
        ),
        migrations.AlterModelOptions(
            name='entrancegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objectphoto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objectterritory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subobject',
            options={},
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='build_year',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='floors_count',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='full_name_kz',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='has_electronic_board',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='has_pavilion',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='is_accessible',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='door_width_ok',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='has_audio_guide',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='has_braille',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='has_call_button',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='has_tactile_path',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='has_visual_info',
        ),
        migrations.RemoveField(
            model_name='entrancegroup',
            name='ramp_slope_ok',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='build_year',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='floors_count',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='full_name_kz',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='objectterritory',
            name='entrance_actual_value',
        ),
        migrations.RemoveField(
            model_name='objectterritory',
            name='entrance_not_required',
        ),
        migrations.RemoveField(
            model_name='objectterritory',
            name='parking_has_disabled_spots',
        ),
        migrations.RemoveField(
            model_name='objectterritory',
            name='parking_not_required',
        ),
        migrations.RemoveField(
            model_name='subobject',
            name='build_year',
        ),
        migrations.RemoveField(
            model_name='subobject',
            name='floors',
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True, verbose_name='Полное юридическое наименование'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование на русском'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='object_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус объекта'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Полигоны координат'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='report_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Фото отчет'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='sending_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.passportstatus', verbose_name='Статус отправки'),
        ),
        migrations.AddField(
            model_name='accessibilityobject',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.street'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='ownership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.ownershipentity'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='responsible_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.responsiblebody'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='sending_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_status', to='directories.passportstatus', verbose_name='Статус отправки'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановка'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True, verbose_name='Полное юридическое наименование'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование на русском'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='object_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус объекта'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Полигоны координат'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='report_photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото отчет'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='sending_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.passportstatus', verbose_name='Статус отправки'),
        ),
        migrations.AddField(
            model_name='historicalaccessibilityobject',
            name='street',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.street'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.activitytype'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.category'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка координат'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='ownership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.ownershipentity'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='responsible_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.responsiblebody'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.district'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка координат'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='activity_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.activitytype'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.category'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка координат'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='ownership_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.ownershipentity'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='responsible_body',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.responsiblebody'),
        ),
        migrations.AlterField(
            model_name='objectterritory',
            name='entrance_width_ok',
            field=models.BooleanField(default=False, verbose_name='Ширина прохода соответствует'),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название под-объекта'),
        ),
        migrations.CreateModel(
            name='StopAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='objects.busstop')),
                ('street_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.streetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StopPavilion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_lighting', models.BooleanField(default=False, verbose_name='Освещение')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pavilion', to='objects.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='StopPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_tactile_tile', models.BooleanField(default=False, verbose_name='Тактильная плитка')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='objects.busstop')),
            ],
        ),
    ]
