# Generated by Django 5.2.13 on 2026-04-18 14:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_alter_accessibilitycategory_options_and_more'),
        ('objects', '0006_alter_busstop_options_alter_entrancegroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppavilion',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='stopplatform',
            name='stop',
        ),
        migrations.AlterModelOptions(
            name='accessibilityobject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalaccessibilityobject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical accessibility object', 'verbose_name_plural': 'historical accessibility objects'},
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='report_photo',
        ),
        migrations.RemoveField(
            model_name='accessibilityobject',
            name='street',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='ownership_type',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='responsible_body',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='sending_status',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='report_photo',
        ),
        migrations.RemoveField(
            model_name='historicalaccessibilityobject',
            name='street',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='description',
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_braille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_call_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrancegroup',
            name='has_visual_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectterritory',
            name='parking_has_disabled_spots',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.district'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='accessibilityobject',
            name='sending_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.passportstatus'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entrancegroup',
            name='has_ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.district'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='full_legal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalaccessibilityobject',
            name='sending_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.passportstatus'),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='image',
            field=models.ImageField(upload_to='objects/'),
        ),
        migrations.AlterField(
            model_name='objectterritory',
            name='entrance_width_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subobject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='InfoTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_audio_guide', models.BooleanField(default=False)),
                ('induction_loop', models.BooleanField(default=False)),
                ('has_visual_info', models.BooleanField(default=False)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_telecom', to='objects.accessibilityobject')),
            ],
        ),
        migrations.CreateModel(
            name='MovementWays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_ok', models.BooleanField(default=False)),
                ('has_handrails', models.BooleanField(default=False)),
                ('tactile_indicators', models.BooleanField(default=False)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movement_ways', to='objects.accessibilityobject')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAccessibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('k_status', models.CharField(default='not_accessible', max_length=20)),
                ('o_status', models.CharField(default='not_accessible', max_length=20)),
                ('z_status', models.CharField(default='not_accessible', max_length=20)),
                ('s_status', models.CharField(default='not_accessible', max_length=20)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='objects.accessibilityobject')),
            ],
            options={
                'unique_together': {('object', 'section')},
            },
        ),
        migrations.CreateModel(
            name='SanitaryRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_accessible', models.BooleanField(default=False)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanitary_rooms', to='objects.accessibilityobject')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_height_ok', models.BooleanField(default=False)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='objects.accessibilityobject')),
            ],
        ),
        migrations.DeleteModel(
            name='StopAccessibility',
        ),
        migrations.DeleteModel(
            name='StopPavilion',
        ),
        migrations.DeleteModel(
            name='StopPlatform',
        ),
    ]
