# Generated by Django 5.2.13 on 2026-04-19 21:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_alter_accessibilitycategory_options_and_more'),
        ('objects', '0007_remove_stoppavilion_stop_remove_stopplatform_stop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'verbose_name': 'Паспорт остановки', 'verbose_name_plural': '2. Паспорта остановок'},
        ),
        migrations.AddField(
            model_name='busstop',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к наименованию/адресу'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='not_in_tx',
            field=models.BooleanField(default=False, verbose_name='Отметить если нет остановки в ТХ'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='ownership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.ownershipentity'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='report_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stops/reports/', verbose_name='Фото отчет'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='responsible_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.responsiblebody'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='sending_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_status', to='directories.passportstatus', verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка координат'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановка'),
        ),
        migrations.CreateModel(
            name='StopAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_dedicated_lane', models.BooleanField(default=False, verbose_name='Наличие выделенной полосы')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='objects.busstop')),
                ('street_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.streetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StopPavilion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_lighting', models.BooleanField(default=False, verbose_name='Наличие освещения')),
                ('has_benches', models.BooleanField(default=False, verbose_name='Наличие скамеек')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pavilion', to='objects.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='StopPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_level_with_bus', models.BooleanField(default=False, verbose_name='В один уровень с дорогой')),
                ('has_tactile_tile', models.BooleanField(default=False, verbose_name='Наличие тактильной плитки')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='objects.busstop')),
            ],
        ),
    ]
