# Generated by Django 5.2.12 on 2026-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип покрытия')),
            ],
            options={
                'verbose_name': 'Категория покрытия',
                'verbose_name_plural': '9. Категории покрытия',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': '10. Улицы',
            },
        ),
        migrations.AlterField(
            model_name='passportstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Статус паспорта'),
        ),
    ]
