# Generated by Django 5.2.13 on 2026-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2196F3', max_length=7, verbose_name='Цвет маркера (HEX)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
        ),
    ]
