# Generated by Django 5.2.13 on 2026-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_alter_activitytype_options_remove_activitytype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код категории')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование на русском')),
                ('name_kz', models.CharField(blank=True, max_length=255, verbose_name='Наименование на казахском')),
                ('description_ru', models.TextField(blank=True, verbose_name='ОПИСАНИЕ (RU)')),
            ],
            options={
                'verbose_name': 'Категория доступности',
                'verbose_name_plural': 'Категории доступности',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='AccessibilityStatus',
        ),
    ]
