# Generated by Django 5.2.13 on 2026-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0009_accessibilitycategory_delete_accessibilitystatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilitycategory',
            options={'verbose_name': 'Категория МГН', 'verbose_name_plural': 'Категории МГН'},
        ),
        migrations.RemoveField(
            model_name='accessibilitycategory',
            name='description_ru',
        ),
        migrations.AlterField(
            model_name='accessibilitycategory',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='accessibilitycategory',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование вида деятельности на казахском'),
        ),
        migrations.AlterField(
            model_name='accessibilitycategory',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Наименование вида деятельности на русском'),
        ),
    ]
